apiVersion: batch/v1

kind: Job

metadata:

  name: mongo-init-replicaset

spec:

  template:

    spec:

      containers:

      - name: mongo-init

        image: docker.io/mongo:latest

        command:

          - "sh"

          - "-c"

          - |

            echo "Waiting for mongo-0 to be ready..."

            until mongosh --host mongo-0.mongo.default.svc.cluster.local:27017 --eval "print(\"waiting...\")"; do

              sleep 2

            done

            echo "Initializing replica set..."

            mongosh --host mongo-0.mongo.default.svc.cluster.local:27017 --eval 'rs.status()' || mongosh --host mongo-0.mongo.default.svc.cluster.local:27017 --eval 'rs.initiate({_id: "rs0", members: [{_id: 0, host: "mongo-0.mongo.default.svc.cluster.local:27017"}, {_id: 1, host: "mongo-1.mongo.default.svc.cluster.local:27017"}, {_id: 2, host: "mongo-2.mongo.default.svc.cluster.local:27017"}]})'

      restartPolicy: OnFailure

  backoffLimit: 4
