apiVersion: storage.k8s.io/v1

kind: StorageClass

metadata:

  name: mongo-storage-class

provisioner: kubernetes.io/aws-ebs

parameters:

  type: gp2

  fsType: ext4

  encrypted: "true"

reclaimPolicy: Retain
