apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: polybot-app
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: 'https://github.com/Berko10/INTPolybotServiceKubernetes/PolybotInfra.git'
    targetRevision: main
    path: .  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
