apiVersion: apps/v1

kind: Deployment

metadata:

  name: yolo5-deployment

spec:

  replicas: 2 

  selector:

    matchLabels:

      app: yolo5

  template:

    metadata:

      labels:

        app: yolo5

    spec:

      containers:

        - name: yolo5

          image: "docker.io/berko1/yolo5k:latest"

          ports:

            - containerPort: 8081

          env:

            - name: BUCKET_NAME

              value: "berko-polybot-docker-bucket"

            - name: SQS_QUEUE_URL

              value: "https://sqs.eu-central-1.amazonaws.com/352708296901/Berko-polybot-queue"

            - name: AWS_REGION

              value: "eu-central-1"

            - name: POLYBOT_URL

              value: "https://polybot.k8s.devops-int-college.com"

            - name: MONGO_USER

              valueFrom:

                secretKeyRef:

                  name: mongo-secret

                  key: username

            - name: MONGO_PASSWORD

              valueFrom:

                secretKeyRef:

                  name: mongo-secret

                  key: password

            - name: MONGODB_URI

              value: "mongodb://$(MONGO_USER):$(MONGO_PASSWORD)@mongo-0.mongo,mongo-1.mongo,mongo-2.mongo:27017/?authSource=admin"

      imagePullSecrets:

        - name: dockerhub-secret

