cat yolo5-service.yaml 

apiVersion: v1

kind: Service

metadata:

  name: yolo5-service

spec:

  selector:

    app: yolo5

  ports:

    - protocol: TCP

      port: 8081  

      targetPort: 8081

  type: ClusterIP 
