apiVersion: apps/v1

kind: Deployment

metadata:

  name: polybot-deployment

  namespace: default

spec:

  replicas: 2

  selector:

    matchLabels:

      app: polybot

  template:

    metadata:

      labels:

        app: polybot

    spec:

      containers:

        - name: polybot

          image: "docker.io/berko1/polybotk:latest"

          ports:

            - containerPort: 8443

          env:

            - name: TELEGRAM_APP_URL

              value: "https://polybot.k8s.devops-int-college.com"

            - name: S3_BUCKET_NAME

              value: "berko-polybot-docker-bucket"

            - name: SQS_QUEUE_URL

              value: "https://sqs.eu-central-1.amazonaws.com/352708296901/Berko-polybot-queue"

            - name: CERTIFICATE_FILE_NAME

              value : certificate.crt

            - name: MONGO_USER

              valueFrom:

                secretKeyRef:

                  name: mongo-secret

                  key: username

            - name: MONGO_PASSWORD

              valueFrom:

                secretKeyRef:

                  name: mongo-secret

                  key: password

            - name: MONGODB_URI

              value: "mongodb://$(MONGO_USER):$(MONGO_PASSWORD)@mongo-0.mongo,mongo-1.mongo,mongo-2.mongo:27017/?authSource=admin"

      imagePullSecrets:

        - name: dockerhub-secret

