apiVersion: batch/v1

kind: CronJob

metadata:

  name: refresh-join-token

spec:

  schedule: "*/10 * * * *"  # כל 10 דקות

  jobTemplate:

    spec:

      template:

        spec:

          restartPolicy: OnFailure

          containers:

          - name: token-generator

            image: amazonlinux  

            command: ["/bin/sh", "-c"]

            args:

              - |

                TOKEN=$(kubeadm token create --print-join-command | awk '{print $5}')

                aws secretsmanager update-secret --secret-id k8s-join-token --secret-string "$TOKEN" --region eu-central-1

          serviceAccountName: token-updater-sa

